import Head from 'next/head';
import { Inter } from 'next/font/google';
import Navbar from '@/components/Navbar';
import Events from '@/components/Events';
import ModalForm from '@/components/ModalForm';
import { EventsContext } from '@/contexts/EventsContext';
import { useContext } from 'react';
import Overlay from '@/components/Overlay';

const inter = Inter({ subsets: ['latin'] });

export default function Home(props) {
  const context = useContext(EventsContext);
  return (
    <>
      <Head>
        <title>Amatak App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-[1500px] relative">
        <Navbar />
        <Events />
        {context.modalOpen && <ModalForm />}
        {context.modalOpen && <Overlay />}
      </main>
    </>
  );
}
